// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztsrrlohzjukekrgmhwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0c3JybG9oemp1a2VrcmdtaHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzE2NzEsImV4cCI6MjA3MDU0NzY3MX0.Mo78hSUivSMk1P6dJSBPw0pVWiVwFYDKZ0LxXjhThtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});